export enum UserActionType {
    GETTING_USER_PROFILE = 'GETTING_USER_PROFILE',
    GETTING_USER_PROFILE_SUCCESS = 'GETTING_USER_PROFILE_SUCCESS',
    GETTING_USER_PROFILE_FAILURE = 'GETTING_USER_PROFILE_FAILURE',

    LOGGING_IN = 'LOGGING_IN',
    LOGGING_IN_SUCCESS = 'LOGGING_IN_SUCCESS',
    LOGGING_IN_FAILURE = 'LOGGING_IN_FAILURE',

    LOGGING_OUT = 'LOGGING_OUT',
    LOGGING_OUT_SUCCESS = 'LOGGING_OUT_SUCCESS',
    LOGGING_OUT_FAILURE = 'LOGGING_OUT_FAILURE',

    CREATING_USER = 'CREATING_USER',
    CREATING_USER_SUCCESS = 'CREATING_USER_SUCCESS',
    CREATING_USER_FAILURE = 'CREATING_USER_FAILURE'
}
